cors:
    originPatterns: http://localhost:8080,http://localhost:3000,http://erudio.com.br
file:
    upload-dir: /UploadDir
security:
    jwt:
        token:
            secret-key: 53cr37
            expire-length: 3600000
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
        username: root
        password:
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
            show-sql: false
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 200MB
            max-request-size: 215MB
    output:
        ansi:
            enabled: ALWAYS
spring-doc:
    pathsToMatch: 
        - /auth/**
        - /api/**/v1/**
    swagger-ui:
        use-root-path: true
